#!/usr/bin/env bash
# Regenerate and package the MANUAL deployment kit:
#   dist/MFOps_manual-kit_1.0/       (tracked, generated by gen_manual_kit.py)
#   dist/MFOps_manual-kit_1.0.zip    (tracked distribution copy; email-safe)
#
# FAIL-CLOSED ON: any script/binary type in the kit, any FORBIDDEN string in
# any kit file, the 737-row expectation (the generator itself stops), or a
# residue hit. SHA256SUMS.txt is written last, over everything.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KIT="$ROOT/dist/MFOps_manual-kit_1.0"

python3 "$ROOT/scripts/gen_manual_kit.py"

BAD="$(find "$KIT" -type f \( -name '*.sh' -o -name '*.ps1' -o -name '*.py' \
       -o -name '*.exe' -o -name '*.msapp' -o -name '*.msapr' \) | sed "s|$KIT/||")"
[ -z "$BAD" ] || { echo "STOP: script/binary types in the manual kit:"; echo "$BAD"; exit 1; }

python3 - "$KIT" "$ROOT" <<'PY'
import os, sys
kit, root = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(root, "scripts"))
from build_msapp import FORBIDDEN
bad = []
for base, _d, files in os.walk(kit):
    for f in files:
        p = os.path.join(base, f)
        for line in open(p, encoding="utf-8", errors="ignore").read().splitlines():
            if "prerelease: allow" in line:
                continue
            for s in FORBIDDEN:
                if s in line:
                    bad.append((os.path.relpath(p, kit), s))
if bad:
    print("STOP: residue in the manual kit:")
    for w, s in bad:
        print(f"  {w}: {s}")
    raise SystemExit(1)
print("residue sweep: clean over the manual kit")
PY

( cd "$KIT" && find . -type f ! -name SHA256SUMS.txt -print0 \
    | sort -z | xargs -0 sha256sum | sed 's|\./||' > SHA256SUMS.txt )

rm -f "$ROOT/dist/MFOps_manual-kit_1.0.zip"
( cd "$ROOT/dist" && zip -qrX "$ROOT/dist/MFOps_manual-kit_1.0.zip" MFOps_manual-kit_1.0 )
sha256sum "$ROOT/dist/MFOps_manual-kit_1.0.zip"
