#!/usr/bin/env python3
"""Emit docs/SHAREPOINT_SCHEMA_MANIFEST.md from scripts/eom_schema.py.

WHY THIS EXISTS SEPARATELY FROM THE DATA DICTIONARY
---------------------------------------------------
The data dictionary describes the model for a reader. This describes the
DEPLOYED ARTEFACT for whoever has to reconcile it against a tenant.

SharePoint internal names are IMMUTABLE. A column created with a display name
containing a space gets an internal name with `_x0020_` in it, permanently, and
every Power Fx reference and every flow expression binds to that internal name
rather than the display name. Renaming the column later changes the display name
and nothing else; recreating it to "tidy" the internal name breaks every
reference silently -- the app does not error, it reads blank.

So: the internal name is the contract. This manifest states it for all 17 lists,
and `tests/test_schema_manifest.py` compares every reference in every formula and
flow against it. A mismatch is a stop condition, not a cleanup task.

Regenerate:
    python3 scripts/gen_schema_manifest.py > docs/SHAREPOINT_SCHEMA_MANIFEST.md
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import eom_schema as S


def emit():
    out = []
    w = out.append
    w("<!-- GENERATED by scripts/gen_schema_manifest.py -- do not edit by hand. -->")
    w("")
    w("# SharePoint schema manifest")
    w("")
    w(f"Schema version **{S.SCHEMA_VERSION}** -- **{len(S.LISTS)} lists**, "
      f"**{S.total_columns()} columns**.")
    w("")
    w("## The internal name is the contract")
    w("")
    w("SharePoint internal names are **immutable**. Power Fx and every flow "
      "expression bind to the internal name, not the display name.")
    w("")
    w("* Renaming a column changes its display name and nothing else. Harmless.")
    w("* **Recreating** a column to give it a nicer internal name breaks every "
      "reference to it -- and breaks it *silently*. The app does not error; it "
      "reads blank, and a required document quietly stops being tracked.")
    w("")
    w("Every internal name below is a plain identifier: no spaces, so no "
      "`_x0020_`, and none over SharePoint's 32-character limit. That is "
      "enforced by `eom_schema.ListDef.validate()`, not by convention.")
    w("")
    w("**If a list already exists on the destination side, created by somebody "
      "else, its internal names may differ from these.** That case is detected "
      "and owned in `deployment/DEPENDENCY_MANIFEST.md`. Do not resolve it by "
      "recreating columns.")
    w("")
    w("## Provisioning")
    w("")
    w("`provisioning/Provision-MFOpsLists.ps1` creates every column from "
      "`provisioning/schema.generated.json` with `StaticName` and `Name` both "
      "set to the internal name below, so the internal name is fixed at "
      "creation and never derived from a display name.")
    w("")
    w("**Indexes are created at provisioning time or never.** SharePoint will "
      "not add an index to a list that has already crossed the 5,000-item list "
      "view threshold, and `MF_EOM_Item` passes that in the first quarter.")
    w("")
    w("---")
    w("")

    for l in S.LISTS:
        w(f"## `{l.name}`")
        w("")
        w(f"**Display name:** {l.title}  ")
        w(f"**Grain:** {l.grain}  ")
        w(f"**Unique key:** {', '.join(l.unique_key)}  ")
        w(f"**Volume estimate:** ~{l.volume_estimate:,} rows  ")
        w(f"**Columns:** {len(l.columns)} -- **indexed:** "
          f"{', '.join(l.indexed_columns) or 'none'}")
        w("")
        if l.volume_estimate > 5000:
            w("> Crosses the SharePoint delegation ceiling. Every production "
              "query against this list must filter on an indexed column.")
            w("")
        w("| Internal name | Display name | Type | Required | Indexed | Choices / default |")
        w("|---|---|---|---|---|---|")
        for c in l.columns:
            choices = ""
            if c.choices:
                choices = "<br>".join(f"`{x}`" for x in c.choices)
            elif c.type == "Boolean":
                choices = "default `0` (false)"
            display = c.name.replace("_", " ")
            w(f"| `{c.name}` | {display} | {c.type} | "
              f"{'YES' if c.required else 'no'} | "
              f"{'YES' if c.indexed else 'no'} | {choices} |")
        w("")

    w("---")
    w("")
    w("## Reconciliation")
    w("")
    w("`tests/test_schema_manifest.py` extracts every SharePoint column "
      "reference from every `.fx` file, every `.pa.yaml` screen and every flow "
      "specification, and compares it against this manifest. An unknown "
      "reference fails the suite.")
    w("")
    w("It cannot check a *tenant*. A column that exists here and not there is "
      "a deployment failure, and `deployment/DEPENDENCY_MANIFEST.md` says who "
      "detects it.")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.stdout.write(emit())
