#!/usr/bin/env python3
"""Emit canvas-app/msapp-src/ — the app source in the EXACT dialect Studio writes.

canvas-app/src is this repository's source of truth and stays as it is. This
generator transliterates it into the Power Apps YAML v3 dialect that
`pac canvas pack --layout SourceCode` consumes and Power Apps Studio itself
saves, so the app can be BUILT rather than pasted.

Every mapping below is evidenced, not guessed:

  evidence class A — read from a genuine Studio-built app (the ALM test app in
      microsoft/PowerApps-Language-Tooling, MSAppStructureVersion 2.4.0) or
      from the official pa.yaml v3 schema in the same repository:
        * `Control: CanvasComponent` for component instances
        * `Variant: AutoLayout` + LayoutDirection for auto-layout containers
        * `Variant: galleryVertical` (named in the gallery template payload)
        * control version suffixes optional:  (@\\d+\\.\\d+\\.\\d+)?
        * `_EditorState.pa.yaml` carrying ScreensOrder / ComponentDefinitionsOrder
  evidence class B — Microsoft Learn's documented modern-control variants
      (Button: Primary/Secondary/Subtle; Text ramp: Body1/Caption1/Subtitle1).
      Wrong ones fail VISIBLY in Studio, not silently.

The output is validated by packing it with Microsoft's own packer, which
parses the YAML (EnableLoadFromYaml), and by unpacking the result and
diffing. Anything the packer rejects is fixed HERE, never in the output.
"""
import os
import re
import shutil
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(ROOT, "canvas-app", "src")
FX = os.path.join(ROOT, "canvas-app", "formulas")
OUT = os.path.join(ROOT, "canvas-app", "msapp-src")

BANNER = """\
# ============================================================================
# GENERATED by scripts/gen_msapp_source.py from canvas-app/src -- do not edit.
# canvas-app/src is the source of truth; regenerate rather than patch.
# ============================================================================
"""

# evidence class A
VARIANT_MAP = {
    "verticalAutoLayoutContainer": ("AutoLayout", "Vertical"),
    "horizontalAutoLayoutContainer": ("AutoLayout", "Horizontal"),
    "verticalGallery": ("galleryVertical", None),
}
# evidence class B -- the documented Fluent ramp / button variants.
TEXT_RAMP = {"Body": "Body1", "Caption": "Caption1", "Subtitle": "Subtitle1"}
BUTTON_OK = {"Primary", "Secondary", "Subtle"}


def transliterate(text):
    lines = text.split("\n")
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]

        # component instances: Control: Component -> CanvasComponent
        line = re.sub(r"(\bControl:\s*)Component\s*$", r"\1CanvasComponent", line)

        m = re.match(r"^(\s*)Variant:\s*([A-Za-z]+)\s*$", line)
        if m:
            indent, variant = m.group(1), m.group(2)
            if variant in VARIANT_MAP:
                new, direction = VARIANT_MAP[variant]
                out.append(f"{indent}Variant: {new}")
                if direction:
                    # LayoutDirection goes into the Properties block that
                    # follows; remember it for injection.
                    out.append(f"{indent}__INJECT_DIRECTION__: {direction}")
                i += 1
                continue
            if variant in TEXT_RAMP:
                out.append(f"{indent}Variant: {TEXT_RAMP[variant]}")
                i += 1
                continue
        out.append(line)
        i += 1

    # Move each __INJECT_DIRECTION__ into the next Properties: block.
    final = []
    pending = None
    for line in out:
        m = re.match(r"^(\s*)__INJECT_DIRECTION__: (\w+)$", line)
        if m:
            pending = m.group(2)
            continue
        final.append(line)
        if pending and re.match(r"^\s*Properties:\s*$", line):
            indent = re.match(r"^(\s*)", line).group(1) + "  "
            final.append(f"{indent}LayoutDirection: =LayoutDirection.{pending}")
            pending = None
    return "\n".join(final)


def named_formulas():
    """The four .fx files concatenated into the App.Formulas property value.

    Order matters and is the same order the paste runbook gives: later files
    reference earlier ones.
    """
    parts = []
    for f in ("App.Formulas.fx", "StatusEngine.fx", "Cascade.fx",
              "Delegation.fx"):
        with open(os.path.join(FX, f), encoding="utf-8") as fh:
            parts.append(f"// ---- {f} " + "-" * (58 - len(f)) + "\n"
                         + fh.read().strip())
    return "\n\n".join(parts)


def app_yaml():
    """App.pa.yaml in the official dialect: Properties only.

    The repository's App.pa.yaml carries repo-convention keys (ScreenOrder,
    DataSources, Formulas file list) that are NOT in the v3 schema; screen
    order goes to _EditorState.pa.yaml and the formula files are inlined into
    the App.Formulas property, which is where Studio keeps named formulas.
    """
    src = open(os.path.join(SRC, "App.pa.yaml"), encoding="utf-8").read()
    onstart = re.search(r"OnStart: \|\n((?:      .*\n|\n)+?)(?=\n    \S|\n\S)",
                        src)
    onstart_body = onstart.group(1).rstrip("\n") if onstart else "      =false"

    formulas = named_formulas()
    ind = " " * 6
    formulas_block = "\n".join(ind + ln if ln.strip() else ""
                               for ln in ("=" + formulas).split("\n"))
    return f"""{BANNER}App:
  Properties:
    StartScreen: =MF_StartScreen
    OnStart: |
{onstart_body}
    Formulas: |
{formulas_block}
"""


def editor_state(screens, components):
    order = ["scrMaintenance", "scrNoAccess", "scrHome", "scrMyPackage",
             "scrOverview", "scrInstallations", "scrExceptions", "scrUpload",
             "scrReview", "scrInstallation", "scrCalendar", "scrActivity",
             "scrAdminRequirements", "scrUnmatched", "scrAccessRequest",
             "scrDiagnostics"]
    assert set(order) == set(screens), set(order) ^ set(screens)
    comp_order = ["cmpStatusBadge", "cmpEmptyState", "cmpMetricCard",
                  "cmpEOMItem", "cmpMetricStrip", "cmpFilterToolbar"]
    assert set(comp_order) == set(components), set(comp_order) ^ set(components)
    body = BANNER + "EditorState:\n  ScreensOrder:\n"
    body += "".join(f"    - {s}\n" for s in order)
    body += "  ComponentDefinitionsOrder:\n"
    body += "".join(f"    - {c}\n" for c in comp_order)
    return body


def main():
    shutil.rmtree(OUT, ignore_errors=True)
    os.makedirs(os.path.join(OUT, "Src", "Components"))

    screens, components = [], []
    for f in sorted(os.listdir(os.path.join(SRC, "Screens"))):
        if f.endswith(".pa.yaml"):
            screens.append(f[:-8])
            text = open(os.path.join(SRC, "Screens", f), encoding="utf-8").read()
            with open(os.path.join(OUT, "Src", f), "w", encoding="utf-8") as fh:
                fh.write(BANNER + transliterate(text))
    for f in sorted(os.listdir(os.path.join(SRC, "Components"))):
        if f.endswith(".pa.yaml"):
            components.append(f[:-8])
            text = open(os.path.join(SRC, "Components", f), encoding="utf-8").read()
            with open(os.path.join(OUT, "Src", "Components", f), "w",
                      encoding="utf-8") as fh:
                fh.write(BANNER + transliterate(text))

    with open(os.path.join(OUT, "Src", "App.pa.yaml"), "w",
              encoding="utf-8") as fh:
        fh.write(app_yaml())
    with open(os.path.join(OUT, "Src", "_EditorState.pa.yaml"), "w",
              encoding="utf-8") as fh:
        fh.write(editor_state(screens, components))

    n = sum(len(files) for _b, _d, files in os.walk(OUT))
    print(f"canvas-app/msapp-src: {n} files "
          f"({len(screens)} screens, {len(components)} components)")


if __name__ == "__main__":
    sys.exit(main())
