#!/usr/bin/env python3
"""Generate dist/MFOps_manual-kit_1.0/ -- the MANUAL deployment kit.

Everything an operator needs to stand up the pilot ENTIRELY by hand in
SharePoint, Power Apps Studio and the Power Automate designer: no solution
import, no Dataverse, no CLI, no provisioning flow.

NOTHING IN THE BUILD SHEETS OR THE FLOW MANUAL IS HAND-TYPED FROM MEMORY:
list sheets derive from scripts/eom_schema.py (the single schema authority),
the EOM-02 manual derives action-by-action from the implemented workflow JSON
in solution/src/Workflows, and the expected-items CSV is generated by the
same EOM-01 engine the tests run -- 737 rows or this script stops.
tests/test_manual_kit.py re-derives the totals and fails the suite if a
sheet ever drifts from the schema.
"""
from __future__ import annotations

import csv
import datetime as dt
import io
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import eom_schema as S                                     # noqa: E402
from generate_expected_items import generate, periods_in_window  # noqa: E402

KIT = os.path.join(ROOT, "dist", "MFOps_manual-kit_1.0")
FLOW_JSON = os.path.join(
    ROOT, "solution", "src", "Workflows",
    "EOM02Submission-AE99D9D1-0DD1-5E66-8361-7E59A52392D8.json")

# The one date every status in the seeded CSV is computed against.
AS_OF = dt.date(2026, 9, 1)

# Dependency order for hand-creation: reference and configuration lists
# first (nothing points at them yet while they are empty), transactional
# lists last. This ORDER is the kit's one editorial decision -- the schema
# does not encode creation order; everything else in the sheets is derived.
BUILD_ORDER = [
    "MF_App_Config", "MF_Feature_Flags", "MF_Installation", "MF_Facility",
    "MF_EOM_Requirement", "MF_Document_Destination", "MF_Non_Duty_Day",
    "MF_Notification_Rule", "MF_Security_Mapping", "MF_Access_Request",
    "MF_Calendar_Event", "MF_EOM_Item", "MF_EOM_Submission",
    "MF_Unmatched_File", "MF_EOM_Status", "MF_EOM_Audit", "MF_App_Event_Log",
]

INTERNAL_NAME_TRAP = """\
> **THE INTERNAL-NAME TRAP, RESTATED.** Type every list name and every column
> name EXACTLY as printed, at creation time, and never rename to fix a typo.
> SharePoint freezes a column's INTERNAL name from the name it is created
> with: create `Installation ID` (with a space) and the internal name is
> `Installation_x0020_ID` forever -- renaming the display name afterwards
> changes nothing underneath, and every formula and flow in this kit
> addresses the internal name. Create it wrong, DELETE it and create it
> again; never rename.
"""


def _writeif(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _type_settings(col):
    t = col.type
    if t == "Choice":
        return ("Choice", "Display choices in: Drop-Down Menu; "
                "Allow 'Fill-in' choices: No")
    if t == "Text":
        return ("Single line of text", "255 characters")
    if t == "Note":
        return ("Multiple lines of text", "Plain text")
    if t == "Number":
        return ("Number", "Decimal places: Automatic")
    if t == "Integer":
        return ("Number", "Decimal places: 0")
    if t == "Currency":
        return ("Currency", "")
    if t == "Boolean":
        return ("Yes/No", "Default: No")
    if t == "DateTime":
        return ("Date and Time", "Include Time: Yes")
    if t == "Date":
        return ("Date and Time", "Include Time: No")
    if t == "URL":
        return ("Hyperlink or Picture", "Format: Hyperlink")
    if t == "Person":
        return ("Person or Group", "Allow selection of: People Only")
    return (t, "")


# --------------------------------------------------------------- sheets
def build_sheets():
    lists = {l.name: l for l in S.LISTS}
    assert set(BUILD_ORDER) == set(lists), (
        "BUILD_ORDER drifted from the schema: "
        f"{set(BUILD_ORDER) ^ set(lists)}")
    totals = []
    for i, name in enumerate(BUILD_ORDER, 1):
        l = lists[name]
        unique = set(l.unique_key or ())
        cols = list(l.columns)
        n_idx = sum(1 for c in cols if c.indexed)
        totals.append((name, l.title, len(cols), n_idx))

        out = io.StringIO()
        out.write(f"# {i:02d} — create list `{l.title}`\n\n")
        out.write(INTERNAL_NAME_TRAP + "\n")
        out.write(f"**Site Contents → New → List → Blank list.** "
                  f"Name it exactly: `{l.title}`\n\n")
        if l.note:
            out.write(f"> {l.note.strip()}\n\n")
        out.write(f"Grain: {l.grain or 'see data model'} · expected volume "
                  f"~{l.volume_estimate:,} rows\n\n" if l.volume_estimate
                  else "\n")

        out.write("## Columns, in creation order\n\n")
        out.write("| # | Internal name (type EXACTLY) | Create as | "
                  "Settings | Required | Choices (verbatim) | Indexed | "
                  "Unique-key part |\n|---|---|---|---|---|---|---|---|\n")
        for n, c in enumerate(cols, 1):
            disp, settings = _type_settings(c)
            choices = "<br>".join(c.choices) if c.choices else ""
            out.write(f"| {n} | `{c.name}` | {disp} | {settings} | "
                      f"{'Yes' if c.required else 'No'} | {choices} | "
                      f"{'**Y**' if c.indexed else 'N'} | "
                      f"{'**Y**' if c.name in unique else 'N'} |\n")

        idx_cols = [c.name for c in cols if c.indexed]
        out.write(f"\n## Indexes — {n_idx} for this list\n\n")
        out.write("List settings → **Indexed columns** → Create a new "
                  "index, once per column below. Simple indexes only; no "
                  "compound indexes in this schema.\n\n")
        for cn in idx_cols:
            out.write(f"- [ ] `{cn}`\n")
        out.write("\n**Create every index NOW, while the list is empty.** "
                  "Past the 5,000-item List View Threshold, adding an index "
                  "to a large list is restricted and not to be counted on.\n")

        out.write(f"\n## VERIFY before moving on\n\n")
        out.write(f"- [ ] List settings shows **{len(cols)} columns you "
                  f"created** (SharePoint's own Title/ID/Modified rows are "
                  f"extra and do not count).\n")
        out.write(f"- [ ] Indexed columns shows **exactly {n_idx}**.\n")
        spot = next((c for c in cols if c.choices), None)
        if spot:
            out.write(f"- [ ] Spot check: `{spot.name}` offers exactly "
                      f"these choices, spelled exactly: "
                      f"{', '.join('`%s`' % v for v in spot.choices)}.\n")
        if unique:
            out.write(f"- [ ] Spot check: the unique-key column(s) "
                      f"{', '.join('`%s`' % u for u in sorted(unique))} "
                      f"exist with the exact internal names above. "
                      f"(Row uniqueness itself is enforced by the flows' "
                      f"idempotency logic, not by a SharePoint unique "
                      f"constraint — do NOT switch 'Enforce unique values' "
                      f"on unless the sheet's settings column says so.)\n")
        req = next((c for c in cols if c.required), None)
        if req:
            out.write(f"- [ ] Spot check: `{req.name}` is marked "
                      f"required.\n")
        _writeif(os.path.join(KIT, "LIST-BUILD-SHEETS",
                              f"{i:02d}-{name}.md"), out.getvalue())
    return totals


# ------------------------------------------------------- expected items
def load_cfg(name):
    with open(os.path.join(ROOT, "configuration", name),
              encoding="utf-8-sig") as fh:
        return list(csv.DictReader(fh))


def expected_items():
    facs = load_cfg("facilities.csv")
    insts = load_cfg("installations.csv")
    r1 = {f["Installation_ID"] for f in facs if f["In_R1_Scope"] == "TRUE"}
    full = [dict(i,
                 Generation_Enabled=("TRUE" if i["Installation_ID"] in r1
                                     else "FALSE"),
                 Registry_Validated_By="manual-kit",
                 Registry_Validated_Date="2026-08-31") for i in insts]
    rows = {}
    for p in periods_in_window("2026-08", "2026-09"):
        r, _ = generate(load_cfg("requirements.csv"), full, facs, p,
                        existing=dict(rows), today=AS_OF,
                        non_duty_days=load_cfg("non-duty-days.sample.csv"))
        rows.update(r)
    if len(rows) != 737:
        raise SystemExit(
            f"STOP: the engine generated {len(rows)} rows, not 737. "
            f"The pilot was resized or a seed drifted -- report the delta, "
            f"do not ship this CSV.")
    ordered = sorted(rows.values(), key=lambda r: r["EOM_Item_ID"])
    fields = list(ordered[0].keys())
    out = os.path.join(ROOT, "configuration", "expected-items-2026-08-09.csv")
    with open(out, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for r in ordered:
            w.writerow({k: ("" if v is None else v) for k, v in r.items()})
    statuses = {}
    for r in ordered:
        statuses[r["Final_Status"]] = statuses.get(r["Final_Status"], 0) + 1
    return out, fields, statuses


# ----------------------------------------------------------- flow manual
def _sub_params(text):
    """@parameters('MF_X (mfops_MF_X)') -> @variables('varMF_X')."""
    import re
    return re.sub(r"(@?)parameters\('(MF_[A-Za-z0-9_]+) \(mfops_[A-Za-z0-9_]+\)'\)",
                  lambda m: f"{m.group(1)}variables('var{m.group(2)}')", text)


DESIGNER_NAME = {
    "InitializeVariable": "Initialize variable",
    "Compose": "Compose (Data Operation)",
    "If": "Condition",
    "Terminate": "Terminate",
    "Response": "Respond to a PowerApp or flow",
    "OpenApiConnection": None,  # named by its operationId below
}
OPERATION_NAME = {
    "GetItems": "SharePoint — Get items",
    "GetItem": "SharePoint — Get item",
    "PostItem": "SharePoint — Create item",
    "PatchItem": "SharePoint — Update item",
    "CreateFile": "SharePoint — Create file",
    "GetFileItems": "SharePoint — Get files (properties only)",
    "HttpRequest": "SharePoint — Send an HTTP request to SharePoint",
}

WHY = {
    "Look_for_a_replay": "WHY THIS EXISTS: the idempotency guard. The app "
        "sends a unique submissionRequestId; if a row already carries it, a "
        "double-click or a retry returns the FIRST result instead of writing "
        "a duplicate file and a duplicate row.",
    "Get_the_callers_scope": "WHY THIS EXISTS: the flow trusts only its own "
        "authenticated caller lookup, never anything the app claims. A "
        "client that can name its own user is not an authorisation system.",
    "Fail_closed_on_the_destination": "WHY THIS EXISTS: fail closed. An "
        "inactive, unverified or missing destination refuses the upload "
        "with DESTINATION_NOT_CONFIGURED rather than guessing a path.",
    "List_the_fiscal_year_folders": "WHY THIS EXISTS: FIND, never CREATE. "
        "The flow locates the existing FY/month folder by listing what is "
        "actually on the site. It never creates folders: a wrong guess "
        "would scatter documents into structures nobody maintains.",
    "Resolve_the_folder": "WHY THIS EXISTS: when no month folder matches, "
        "the file goes to the configured ROOT and the submission is flagged "
        "Needs_Filing = TRUE with a Filing_Note saying what was looked "
        "for. NOTHING ERRORS -- the Exceptions screen surfaces the count, "
        "and a human files the document one level down.",
    "Supersede_the_current_version": "WHY THIS EXISTS: versioning. The "
        "previous current submission flips Is_Current = FALSE; history is "
        "kept, never overwritten.",
    "Confirm_or_fail_loudly": "WHY THIS EXISTS: the flow never reports "
        "success it cannot prove. If the confirmation read-back fails, the "
        "app shows SUBMISSION_NOT_CONFIRMED instead of a silent maybe.",
}


def flow_manual():
    with open(FLOW_JSON, encoding="utf-8") as fh:
        d = json.load(fh)
    defn = d["properties"]["definition"]
    trig = defn["triggers"]["Request"]
    flow_params = [p.split(" (")[0] for p in defn.get("parameters", {})
                   if p.startswith("MF_")]

    out = io.StringIO()
    out.write("# EOM-02 Submission — manual rebuild, click by click\n\n")
    out.write("Derived action-by-action from the implemented workflow JSON "
              "(`solution/src/Workflows/EOM02Submission-*.json`). Nothing "
              "here is from memory. Build it in the browser designer: "
              "Power Automate → Create → **Instant cloud flow** → trigger "
              "**PowerApps (V2)** → name it `EOM-02 Submission`.\n\n")
    out.write("In this manual edition every solution environment variable "
              "becomes a **flow variable initialized at the top**. Fill "
              "each from your own links sheet.\n\n")

    out.write("## Step 0 — the trigger contract (PowerApps V2 inputs)\n\n")
    out.write("Add one **Text** input per property, named exactly:\n\n")
    for pname, spec in trig["inputs"]["schema"]["properties"].items():
        out.write(f"- [ ] `{pname}`"
                  + (f" (shown as \"{spec['title']}\")" if spec.get("title")
                     else "") + "\n")
    out.write("\nThe app calls `EOM02_Submission.Run(...)` with these in "
              "this order; a missing or renamed input breaks the call "
              "visibly in Studio, which is the good failure mode.\n\n")

    out.write("## Step 0b — Initialize the operator variables\n\n")
    out.write("One **Initialize variable** action per row, Type = String, "
              "placed before everything else. Every value is **OPERATOR "
              "VALUE — from your links sheet**; none ships in this kit.\n\n")
    out.write("| Variable name | Holds |\n|---|---|\n")
    for p in flow_params:
        out.write(f"| `var{p}` | your {p.replace('MF_', '').replace('_', ' ')}"
                  f" — OPERATOR VALUE |\n")
    out.write("\n")

    counter = [0]

    def emit(actions, depth, branch=""):
        order = sorted(actions.items(),
                       key=lambda kv: 0 if not kv[1].get("runAfter") else 1)
        # Preserve chain order by walking runAfter successors.
        emitted, remaining = [], dict(actions)
        chain = [n for n, a in actions.items() if not a.get("runAfter")]
        while chain:
            name = chain.pop(0)
            if name in emitted:
                continue
            emitted.append(name)
            nxt = [n for n, a in remaining.items()
                   if name in (a.get("runAfter") or {})]
            chain = nxt + chain
        for name in emitted:
            node = actions[name]
            counter[0] += 1
            t = node.get("type")
            disp = DESIGNER_NAME.get(t) or t
            if t == "OpenApiConnection":
                op = node["inputs"]["host"].get("operationId", "")
                conn = node["inputs"]["host"].get("connectionName", "")
                disp = OPERATION_NAME.get(op, f"{conn} — {op}")
            pretty = name.replace("_", " ")
            h = "#" * min(3 + depth, 6)
            out.write(f"{h} {counter[0]}. {branch}Add **{disp}** — rename "
                      f"it exactly: `{pretty}`\n\n")
            if name in WHY:
                out.write(f"> {WHY[name]}\n\n")
            ra = node.get("runAfter") or {}
            if ra:
                for prev, conds in ra.items():
                    out.write(f"Run after: `{prev.replace('_', ' ')}` "
                              f"[{', '.join(conds)}]\n\n")
            if t == "If":
                expr = json.dumps(node.get("expression", {}), indent=2)
                out.write("Condition (use **Edit in advanced mode** and "
                          "paste verbatim):\n\n```\n"
                          + _sub_params(expr) + "\n```\n\n")
            inputs = node.get("inputs")
            params = inputs.get("parameters") if isinstance(inputs, dict) \
                else None
            if t in ("InitializeVariable",):
                out.write("Inputs:\n\n```json\n"
                          + _sub_params(json.dumps(node.get("inputs", {}),
                                                   indent=2)) + "\n```\n\n")
            elif t in ("Compose", "Response", "Terminate"):
                out.write("Inputs (paste each expression verbatim):\n\n"
                          "```json\n"
                          + _sub_params(json.dumps(inputs, indent=2))
                          + "\n```\n\n")
            elif params:
                out.write("| Parameter | Value (verbatim) |\n|---|---|\n")
                for k, v in params.items():
                    if k == "$authentication" or k.startswith("$auth"):
                        continue
                    vv = _sub_params(json.dumps(v)) if not isinstance(v, str) \
                        else _sub_params(v)
                    out.write(f"| `{k}` | `{vv}` |\n")
                out.write("\n")
            for key, label in (("actions", "IF TRUE: "),):
                sub = node.get(key)
                if sub:
                    emit(sub, depth + 1, label)
            els = (node.get("else") or {}).get("actions")
            if els:
                emit(els, depth + 1, "IF FALSE: ")

    out.write("## The actions, in order\n\n")
    emit(defn["actions"], 0)

    out.write("""
## Test procedure — one synthetic submission

1. From the app (or the flow's Test pane) call the flow with a synthetic
   `submissionRequestId` (any fresh GUID-like string), a real pilot
   `installationId`/`reportingPeriod`/`requirementId` from your seeded
   data, and a small test file.
2. EXPECT: one new row in your Submission list with `Is_Current = Yes`,
   `Submission_Request_ID` equal to what you sent, and
   `SharePoint_Unique_ID` populated.
3. EXPECT: the file lands in the destination's matched month folder --
   or, if no month folder matches, at the configured ROOT with
   `Needs_Filing = Yes` and a `Filing_Note`. Either is correct behaviour;
   a file anywhere else is not.
4. Run the SAME call again, same `submissionRequestId`. EXPECT: no second
   row, no second file -- the response returns the first result
   (SUBMISSION_REPLAY). That is the idempotency guard working.
5. NOT TESTABLE LOCALLY, verified only here, in your tenant: connector
   auth, folder listings against the real site, and write permissions.
""")
    _writeif(os.path.join(KIT, "FLOW-BUILD", "EOM-02-manual.md"),
             out.getvalue())
    return counter[0]


def deferred_pages():
    pages = {
        "EOM-01-deferred.md": (
            "EOM-01 Expected Package — DEFERRED FOR THE MANUAL PILOT",
            "The generator flow is not built by hand in this kit. Its "
            "output for 2026-08 and 2026-09 is generated OFFLINE by the "
            "same engine the test suite runs and shipped as "
            "`CSV-IMPORT/expected-items-2026-08-09.csv` (exactly 737 "
            "rows). Load that CSV instead of building the flow. When the "
            "solution deployment happens later, the imported EOM-01 takes "
            "over and its idempotency key means it will NOT duplicate "
            "these 737 rows."),
        "EOM-03-deferred.md": (
            "EOM-03 Reconciliation — DEFERRED FOR THE MANUAL PILOT",
            "Replaced by MANUAL REVIEW during the pilot: statuses in the "
            "seeded CSV are computed as of the kit's stated as-of date "
            "and do not refresh on their own. The reviewer works from the "
            "app's queues and the lists directly. Expect statuses to be "
            "stale until either this flow exists or rows are edited by "
            "the EOM-02 flow on submission."),
        "EOM-04-deferred.md": (
            "EOM-04 Notifications — DEFERRED FOR THE MANUAL PILOT",
            "Replaced by NOTHING, deliberately. NotificationsEnabled ships "
            "FALSE and no notification is sent during the manual pilot. "
            "Do not improvise reminder flows against these lists; a "
            "notification storm against live identities is not "
            "recoverable by turning a flag off."),
    }
    for fname, (title, body) in pages.items():
        _writeif(os.path.join(KIT, "FLOW-BUILD", fname),
                 f"# {title}\n\n{body}\n")


SCREEN_CHECKS = [
    ("scrMaintenance", "the support message from MF App Config renders"),
    ("scrNoAccess", "the request-access button renders"),
    ("scrHome", "the navigation list on the left renders and the period "
                "selector shows the open period"),
    ("scrMyPackage", "the six column headings appear: Requirement, "
                     "Frequency, Suspense, Submitted, AFSVC status, Action"),
    ("scrOverview", "four metric cards appear with the scope qualifier "
                    "beneath them"),
    ("scrInstallations", "a row shows 'N of M accepted' -- a fraction, "
                         "never a bare count"),
    ("scrExceptions", "three tabs appear, each with its own count in "
                      "brackets"),
    ("scrUpload", "the file picker is an Add picture / attachment control, "
                  "NOT the Attachments control (the Submit button errors "
                  "until section 5's flow is attached -- expected)"),
    ("scrReview", "the four decision buttons appear: Accept, Return, "
                  "Wrong document, N/A"),
    ("scrInstallation", "the facility list for one installation renders"),
    ("scrCalendar", "the month grid renders and shows non-duty days"),
    ("scrActivity", "the audit gallery renders"),
    ("scrAdminRequirements", "the requirement table renders with "
                             "Authority_Status shown"),
    ("scrUnmatched", "the classification form renders with no free-text "
                     "requirement field"),
    ("scrAccessRequest", "the scope cascade renders and is empty until an "
                         "installation is chosen"),
    ("scrDiagnostics", "the schema version comparison renders"),
]


def canvas_runbook():
    titles = [l.title for l in S.LISTS]
    out = io.StringIO()
    out.write("""# Canvas app — standalone paste runbook (Path C, manual edition)

This app is built OUTSIDE any solution: **Apps → New app → Canvas →
Tablet**, name it `Mission Feeding Operations`. That is deliberate for the
manual pilot -- no solution import and no Dataverse are involved. **State
plainly and up front:** if a solution deployment happens later, the app is
recreated INSIDE the solution at that point (the same content re-paste,
about an hour). Nothing you build now is wasted learning; every formula,
screen and habit transfers verbatim.

## 1. Add the data sources — 18 now, the 19th later

The full app binds 19 sources. Here that is **17 SharePoint lists + the
Office 365 Users connector = 18**, added now; the 19th is the **EOM-02
flow, which does not exist yet** -- you build it in `FLOW-BUILD/
EOM-02-manual.md` AFTER the screens, then return to Studio and attach it
from the **Power Automate pane** (left rail) to the app. The Submit
button's formula errors until then; that is the expected order, not a
mistake.

Data pane → Add data → SharePoint → your site → add each list by its
exact name:

""")
    for t in titles:
        out.write(f"- [ ] `{t}`\n")
    out.write("- [ ] Connector: **Office 365 Users**\n")
    out.write("""
**Check:** the Data pane lists 18 entries and none is suffixed `_1`
(a `_1` means a name was mistyped at list creation -- fix the LIST, not
the app).

## 2. Paste the formulas, in this order

**App → Formulas.** Paste the four files end to end, in this order --
later files reference earlier ones, so any other order produces errors
that are real but misleading:

```
  1. formulas/App.Formulas.fx
  2. formulas/StatusEngine.fx
  3. formulas/Cascade.fx
  4. formulas/Delegation.fx
```

**Check:** the formula bar reports no errors, and `gblSchemaVersion`
resolves to `5.0` once `MF App Config` is seeded. One reference will
stay red until section 5: `EOM02_Submission` -- expected.

## 3. Create the 6 components (Insert → Components), before any screen

Paste each from `src/Components/`, in this order:
`cmpStatusBadge`, `cmpEmptyState`, `cmpMetricCard`, `cmpMetricStrip`,
`cmpFilterToolbar`, `cmpEOMItem`.

**Check:** `cmpStatusBadge` renders text, an icon and a colour together --
never colour alone.

## 4. Create the 16 screens, in this order, one visible check each

| # | Screen | Paste from | The one visible check |
|---:|---|---|---|
""")
    for i, (scr, check) in enumerate(SCREEN_CHECKS, 1):
        out.write(f"| {i} | `{scr}` | `src/Screens/{scr}.pa.yaml` | "
                  f"{check} |\n")
    out.write("""
## 5. Build the flow, then come back

Build EOM-02 per `FLOW-BUILD/EOM-02-manual.md`. Then in Studio:
**Power Automate pane → Add flow → EOM-02 Submission.** The red
`EOM02_Submission` references resolve; the Submit path is live.

## 6. Start screen, save, publish

- **App → StartScreen** is `=MF_StartScreen` from section 2 -- confirm it.
- Set the app **icon and description**, run the **Accessibility
  checker** and clear what it raises, then **Save** and **Publish**.
- Share per the guide: app to the pilot **security group** as User; the
  EOM-02 flow **Run-only** to the same group with connections set to
  "Use this connection"; SharePoint list permissions granted separately
  -- sharing the app grants nothing in SharePoint.
""")
    _writeif(os.path.join(KIT, "CANVAS-MANUAL", "PASTE-RUNBOOK.md"),
             out.getvalue())


def build_guide(totals, statuses):
    out = io.StringIO()
    out.write(f"""# MANUAL BUILD GUIDE — Mission Feeding Operations pilot, entirely by hand

Everything here happens in SharePoint, Power Apps Studio and the Power
Automate designer. **No solution import. No Dataverse. No CLI. No
temporary provisioning flow.** Work the phases in order; every step ends
in something you can SEE, and the next phase assumes you saw it.

{INTERNAL_NAME_TRAP}

## Phase 1 — create the 17 lists

Work `LIST-BUILD-SHEETS/` in file order (01 → 17); the order is
dependency order. Do not skip ahead: transactional lists come last for a
reason.

- [ ] All 17 lists exist, named exactly as the sheets print them.
  **Verify:** Site Contents shows 17 new lists.

## Phase 2 — columns

Each sheet's column table, top to bottom, typing internal names exactly.

- [ ] Every sheet's column count matches.
  **Verify:** each sheet's VERIFY block, ticked.

## Phase 3 — indexes, while every list is still empty

- [ ] Every sheet's index list created, counts matching.
  **Verify:** sign `VERIFICATION.md` -- every row PASS, then and only
  then: `SAFE TO LOAD CONFIGURATION: YES`.

Per-list totals (derived from the schema; the suite fails if this table
drifts):

| # | List | Columns | Indexes |
|---:|---|---:|---:|
""")
    for i, (name, title, nc, ni) in enumerate(totals, 1):
        out.write(f"| {i:02d} | `{title}` | {nc} | {ni} |\n")
    out.write(f"| | **TOTAL** | **{sum(t[2] for t in totals)}** | "
              f"**{sum(t[3] for t in totals)}** |\n")
    status_line = ", ".join(f"{v} × {k}" for k, v in sorted(statuses.items()))
    out.write(f"""
## Phase 4 — CSV seeds (only after VERIFICATION.md says YES)

Follow `CSV-IMPORT/IMPORT-ORDER.md` -- grid-view paste only, **never
"New list → From Excel"**, row-count check after every paste.

- [ ] Config, flags, installations, facilities, requirements,
  destinations, notification rules pasted; counts match.
- [ ] `expected-items-2026-08-09.csv` pasted into `MF EOM Item`:
  **737 rows**, statuses as generated ({status_line}, as of {AS_OF}).
  These do NOT refresh on their own in the manual pilot (EOM-03 is
  deferred); EOM-02 updates a row when a submission lands.
  **Verify:** the list shows 737 items.

## Phase 5 — your security row

- [ ] Create YOUR row in `MF Security Mapping` (UPN = your account,
  scope and role per the sample CSV's column layout -- the sample rows
  themselves are never pasted).
  **Verify:** after Phase 6, the app opens onto Home, not No Access.

## Phase 6 — canvas app (standalone Path C)

`CANVAS-MANUAL/PASTE-RUNBOOK.md`, sections 1–4. The Submit path stays
red until Phase 7 -- expected.

- [ ] 18 data sources, 4 formula files, 6 components, 16 screens, each
  screen's visible check ticked.

## Phase 7 — the EOM-02 flow, then attach it

`FLOW-BUILD/EOM-02-manual.md`, click by click, expressions verbatim.
EOM-01/03/04 are deferred (one page each in `FLOW-BUILD/` says what
replaces them: the CSV; manual review; nothing, deliberately).

- [ ] Flow built and the synthetic-submission test at the end of the
  manual passed: one row, one file, and the replay attempt returned the
  first result instead of duplicating.
- [ ] Flow attached in Studio (runbook section 5); Submit resolves.

## Phase 8 — pilot checks

- [ ] Save, publish, icon/description, Accessibility checker
  (runbook section 6).
- [ ] Share: app → security group as User; flow → Run-only, "Use this
  connection"; SharePoint permissions granted separately.
- [ ] A base-scoped tester sees Home / My Package / Calendar only, and
  their own installation's items only.
- [ ] One real pilot upload lands where `deployment` worksheets say it
  should. NOT TESTABLE LOCALLY -- only your tenant answers this.
""")
    _writeif(os.path.join(KIT, "MANUAL-BUILD-GUIDE.md"), out.getvalue())


# ------------------------------------------------------------------ main
def main():
    if os.path.isdir(KIT):
        shutil.rmtree(KIT)

    totals = build_sheets()
    csv_path, fields, statuses = expected_items()
    n_actions = flow_manual()
    deferred_pages()

    n_lists = len(totals)
    n_cols = sum(t[2] for t in totals)
    n_idx = sum(t[3] for t in totals)
    assert (n_lists, n_cols, n_idx) == (17, 286, 90), (n_lists, n_cols, n_idx)

    # ---- CSV-IMPORT ----
    seeds = [f for f in sorted(os.listdir(os.path.join(ROOT, "configuration")))
             if f.endswith(".csv") and ".sample." not in f]
    os.makedirs(os.path.join(KIT, "CSV-IMPORT"), exist_ok=True)
    counts = {}
    for f in seeds:
        src = os.path.join(ROOT, "configuration", f)
        shutil.copy(src, os.path.join(KIT, "CSV-IMPORT", f))
        with open(src, encoding="utf-8-sig") as fh:
            counts[f] = sum(1 for _ in fh) - 1

    status_lines = "\n".join(f"  {k}: {v} rows"
                             for k, v in sorted(statuses.items()))
    imp = io.StringIO()
    imp.write("# CSV import — grid-view paste, list by list\n\n")
    imp.write("**Never use \"New list → From Excel\"** — it creates its own "
              "columns with its own internal names and silently orphans "
              "every formula in this kit. The lists already exist (the "
              "build sheets made them); these CSVs fill them.\n\n"
              "Per CSV: open the target list → **Edit in grid view** → in "
              "a spreadsheet, arrange the CSV's columns into the SAME "
              "order as the grid → copy the data rows → click the first "
              "empty cell → paste → wait for every cell to commit → "
              "count.\n\n")
    imp.write("| CSV | Target list | Rows to paste | After paste, list "
              "shows |\n|---|---|---:|---|\n")
    title_by_csvish = {
        "app-config.csv": "MF App Config",
        "feature-flags.csv": "MF Feature Flags",
        "installations.csv": "MF Installation",
        "facilities.csv": "MF Facility",
        "requirements.csv": "MF EOM Requirement",
        "document-destinations.csv": "MF Document Destination",
        "notification-rules.csv": "MF Notification Rule",
        "pilot-onboarding.csv": "(worksheet — read, do not paste)",
        "qrg-data-quality.csv": "(worksheet — read, do not paste)",
        "expected-items-2026-08-09.csv": "MF EOM Item",
    }
    for f in seeds:
        tgt = title_by_csvish.get(f, "(see guide)")
        imp.write(f"| `{f}` | {tgt} | {counts[f]} | "
                  f"{counts[f]} items |\n")
    imp.write(f"""
## expected-items-2026-08-09.csv — read this before pasting

Generated OFFLINE by the same EOM-01 engine the test suite runs: full R1
scope (43 installations, 67 Legacy facilities), periods 2026-08 and
2026-09, **exactly 737 rows**. Statuses are computed by the status engine
**as of {AS_OF.isoformat()}** and come out:

{status_lines}

They will NOT refresh on their own during the manual pilot (EOM-03 is
deferred); EOM-02 updates a row when a submission lands, and the rest
stay as seeded until reconciliation exists. That is expected, not a
defect. Blank cells in the CSV are deliberate nulls — paste them as
empty, never as the text "null".
""")
    _writeif(os.path.join(KIT, "CSV-IMPORT", "IMPORT-ORDER.md"),
             imp.getvalue())

    # ---- CANVAS-MANUAL ----
    shutil.copytree(os.path.join(ROOT, "canvas-app", "src"),
                    os.path.join(KIT, "CANVAS-MANUAL", "src"))
    shutil.copytree(os.path.join(ROOT, "canvas-app", "formulas"),
                    os.path.join(KIT, "CANVAS-MANUAL", "formulas"))

    # ---- VERIFICATION ----
    ver = io.StringIO()
    ver.write("# VERIFICATION — sign this before any CSV touches any "
              "list\n\n**Loading configuration before this gate is signed "
              "is forbidden.** An index missed here is found now, while "
              "every list is empty and every index is still cheap to "
              "create.\n\n")
    ver.write("| # | List | Columns expected | Columns found | Indexes "
              "expected | Indexes found | PASS |\n"
              "|---|---|---:|---|---:|---|---|\n")
    for i, (name, title, nc, ni) in enumerate(totals, 1):
        ver.write(f"| {i:02d} | `{title}` | {nc} |    | {ni} |    |    |\n")
    ver.write(f"| | **TOTAL** | **{n_cols}** | | **{n_idx}** | | |\n\n")
    ver.write("The six lists that will grow past 5,000 rows, where a "
              "missing index hurts most:\n\n")
    for nm, exp in (("MF_EOM_Item", 13), ("MF_EOM_Submission", 13),
                    ("MF_EOM_Status", 8), ("MF_Security_Mapping", 8),
                    ("MF_App_Event_Log", 6), ("MF_EOM_Audit", 4)):
        actual = dict((t[0], t[3]) for t in totals)[nm]
        assert actual == exp, (nm, actual, exp)
        ver.write(f"- [ ] `{nm}`: **{exp}** indexes\n")
    ver.write("\n```\nSAFE TO LOAD CONFIGURATION:  YES / NO\n"
              "Signed:                      ____________  Date: ______\n"
              "```\n\nYES only when every row above reads PASS. "
              "Row-level behaviour in the tenant (throttling, threshold "
              "behaviour at 5,000+) is NOT TESTABLE LOCALLY and is not "
              "claimed here.\n")
    _writeif(os.path.join(KIT, "VERIFICATION.md"), ver.getvalue())

    canvas_runbook()
    build_guide(totals, statuses)

    with open(os.path.join(KIT, "kit-facts.json"), "w",
              encoding="utf-8") as fh:
        json.dump({"lists": n_lists, "columns": n_cols, "indexes": n_idx,
                   "expected_rows": 737, "as_of": AS_OF.isoformat(),
                   "statuses": statuses, "flow_actions": n_actions,
                   "per_list": [[t[0], t[2], t[3]] for t in totals]},
                  fh, indent=1)
    print(f"kit: {KIT}")
    print(f"  {n_lists} lists / {n_cols} columns / {n_idx} indexes; "
          f"expected-items rows: 737; statuses: {statuses}; "
          f"flow actions documented: {n_actions}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
